---

- name: Get OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- name: Get Icinga2 package key
  apt_key: url={{ icinga2_key }} state=present
  tags: pkg

- name: Get Debmon package Key
  apt_key: url={{ icinga2_debmon_apt_key }} state=present
  tags: pkg

- name: Get Icinga2 Repos
  apt_repository: repo={{ item }} state=present
  with_items: "{{ icinga2_deb_repos }}"
  tags: pkg

- name: Get Debmon package repo
  apt_repository: repo={{ icinga2_debmon_apt_repository }} state=present

- name: Update apt-get cache
  apt: update_cache=yes cache_valid_time=86400
  tags: pkg
