---

galaxy_info:
  author: D2SI, adapted from Icinga2 official roles
  company: EpiConcept
  description: Install and configure Icinga2
  license: GPLv2
  min_ansible_version: 2.0
  platforms:
    - name: Debian
      versions:
        - all
  categories:
    - system
    - monitoring
dependencies: []
